language: python
python:
  - "2.7"
# command to install dependencies
install: 
    - "pip install -r .travis_requirements.txt"
    - "python setup.py install"
# command to run tests
script: coverage run --source=automate py.test
after_success: coveralls
